#!/bin/bash
source "/home/constantin/sms/functions"
# файл для запуска по расписанию 
# берем файл с фтп и запускаем обработку и загрузку в бд
ftp -in  ftp://j880085_wp3:shE6Wctw58Q@159dz.spectrum.myjino.ru/site/getpu/inSMS/IPK.zip

mak_gud_xml

fill_base

# ну и все..
