#!/bin/bash
status="$1"
file="$2"
# имя файла
flnm=${file:24}

case "$1" in
  RECEIVED)
    FILE=`mktemp /tmp/smsd_XXXXXX`
    # заголовок, телефон
    header=`head -13 $file | grep -e "^From: " -e "^Sent: " -e "^Received: "`
    from=`head -13 $file | grep -e "^From: " | awk '{print $2}'`

    if grep "Alphabet: UCS2" $file > /dev/null ; then
                message=`tail -n +14 $file | iconv -f UCS-2BE -t UTF-8`
        else
                message=`tail -n +14 $file`
        fi
        # перекладываем сюда с преобразованной кодировкой сообщения, понадобится для отправки об неверном вводе данных
        # и для получения показаний (заносится в переменную trfile)
        echo -e "$header\n$message\n" > /var/spool/sms/conv/$flnm
        # паралельно все пишем в лог
        echo -e "$header\n$message\n" >> /var/log/smsd/sms.log
    ;;
  *)
    echo "$*" >>/var/log/smsd/others.log
;;
esac

# проверяем корректность принятого смс
trfile="/var/spool/sms/conv/$flnm"
if !((grep -i "^лс:" $trfile > /dev/null) && (grep -i "^эл:" $trfile > /dev/null))
then
    # преобразовываем и отправляем сообщение о неверном вводе
    echo -e "Неправильный формат СМС!\nПисать:\nЛС:88888888\nЭЛ:555\nХВ:444\nГВ:333" > /var/spool/sms/conv/send_er.sms
    echo -e "To: $from\nAlphabet: UCS2\n" > /var/spool/sms/outgoing/send_er.sms
    iconv -f UTF-8 -t UCS-2BE /var/spool/sms/conv/send_er.sms >> /var/spool/sms/outgoing/send_er.sms
    # при фуфле в смс выходим
    exit
fi

lsch=`head $trfile | grep -i "^лс:"`
ele=`head $trfile | grep -i "эл:"`
hov=""
gov=""

if grep -i "хв:" $trfile > /dev/null ; then
  hov=`head $trfile | grep -i "^хв:"`
fi
if grep -i "гв:" $trfile > /dev/null ; then
  gov=`head $trfile | grep -i "^гв:"`
fi

# записываем в файлы в outgoing для ок ответа и в tomail для отправки эл.почтой и на фтп
echo -e "От вас приняты показания:\n$lsch;$ele;$hov;$gov" > /var/spool/sms/conv/$flnm
echo -e "To: $from\nAlphabet: UCS2\n" > /var/spool/sms/outgoing/$flnm
iconv -f UTF-8 -t UCS-2BE /var/spool/sms/conv/$flnm >> /var/spool/sms/outgoing/$flnm
echo "$lsch;$ele;$hov;$gov;Телефон:+$from" > /home/constantin/sms/tomail/$flnm
message="$lsch;$ele;$hov;$gov;Телефон:+$from"
echo -e "$message" | mail -s -r info@onlight.pro "Incoming SMS from +$from" in@vivaluks.ru
# на фтп не вкуриваются пути, только имя файла
cd /home/constantin/sms/tomail
ftp -in -u ftp://user:passQ@ftp-srv.ru/uploads/ $flnm


