#!/bin/bash
status="$1"
file="$2"
# имя файла будет /var/spool/sms/incoming/GSM1.0eu5Pv"
flnm=${file: -11}

case "$1" in
  RECEIVED)
    FILE=`mktemp /tmp/smsd_XXXXXX`

    header=`head -13 $file | grep -e "^From: " -e "^Sent: " -e "^Received: "`
    from=`head -13 $file | grep -e "^From: " | awk '{print $2}'`

    if grep "Alphabet: UCS2" $file > /dev/null ; then
                message=`tail -n +14 $file | iconv -f UCS-2BE -t UTF-8`
        else
                message=`tail -n +14 $file`
    fi
        echo -e "$header\n$message\n" > /var/spool/sms/conv/$flnm
# паралельно все пишем в лог
        echo -e "$header\n$message\n" >> /var/log/smsd/sms.log
# проверяем корректность принятого смс
trfile="/var/spool/sms/conv/$flnm"
if ! ( grep -i "^лс:" $trfile > /dev/null && grep -i "^эл:" $trfile > /dev/null )
    then
    echo -e "Неправильный формат СМС!\nПисать:\nЛС:88888888\nЭЛ:555\nХВ:444\nГВ:333" > /var/spool/sms/conv/err_mess.sms
    echo -e "To: $from\nAlphabet: UCS2\n" > /var/spool/sms/conv/send_er.sms
    iconv -f UTF-8 -t UCS-2BE /var/spool/sms/conv/err_mess.sms >> /var/spool/sms/conv/send_er.sms
    mv /var/spool/sms/conv/send_er.sms /var/spool/sms/outgoing/
    # при фуфле в смс выходим
    exit 0
fi
  lsch=`head $trfile | grep -i "^лс:"`
  ele=`head $trfile | grep -i "эл:"`
  hov=""
  gov=""
  if grep -i "хв:" $trfile > /dev/null ; then
    hov=`head $trfile | grep -i "^хв:"`
  fi
  if grep -i "гв:" $trfile > /dev/null ; then
    gov=`head $trfile | grep -i "^гв:"`
  fi

  # записать в файлы и положить их в outgoing для ок ответа и в tomail 
  # для отправки ответа клиенту и на почту и ftp для учета данных

  echo -e "От вас приняты показания:\n$lsch;$ele;$hov;$gov" > /var/spool/sms/conv/mes$flnm
  echo -e "To: $from\nAlphabet: UCS2\n" > /var/spool/sms/conv/$flnm
  iconv -f UTF-8 -t UCS-2BE /var/spool/sms/conv/mes$flnm >> /var/spool/sms/conv/$flnm
  mv /var/spool/sms/conv/$flnm /var/spool/sms/outgoing/
  echo "$lsch;$ele;$hov;$gov;Телефон:+$from" > /home/constantin/sms/tomail/$flnm
  rm /var/spool/sms/conv/mes$flnm
  # отправка на почту почему то не работает 
  message="$lsch;$ele;$hov;$gov;Телефон:+$from"
  # и здесь отправка дубля показаний на эл.почту
  echo -e "$message" | mail -s -r ck@onlight.pro "Incoming SMS from +$from" in@vivaluks.ru
  # на фтп не вкуриваются пути, только имя файла
  cd /home/constantin/sms/tomail
  ftp -in -u ftp://user:passQ@ftp-srv.ru/uploads/ $flnm
    ;;
  USSD)
    # сигнализировать про снижение баланса
    cp /var/spool/sms/incoming/$file /home/constantin/sms/
    ;;  
  *)
    echo "$*" >>/var/log/smsd/others.log
    ;;
esac



